name: Java CI with Gradle

on: [ push, workflow_dispatch ]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: docker run -d -p 27017:27017 --name mongoSvr mongo:5.0.6-focal mongod --replSet rs0 --port 27017
      - run: wait-for-it --service mongodb://mongoSvr:27017
      - run: docker exec -i mongoSvr mongo --eval "rs.initiate()"
      - run: docker logs mongoSvr
        if: always()
      - run: docker inspect mongoSvr
        if: always()
