name: Java CI with Gradle

on: [ push, workflow_dispatch ]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: addnab/docker-run-action@v3
        with:
          image: mongo:5.0
          options: -p 27017:27017
          run: mongosh mongodb://localhost:27017/test -f "mongo-init.js"

