name: Java CI with Gradle

on: [ push, workflow_dispatch ]
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker run --name some-mongo -d -p 27017:27017 mongo:5.0 --config mongod.cfg
      - run: docker logs some-mongo
      - run: mongosh mongodb://localhost:27017/test?replicaSet=rs0 -f "mongo-init.js"

